# Permalinks
permalink:          /:title
paginate:           5
paginate_path:      "page:num"

# Setup
title:              LiTHe kod
tagline:            ''
description:        '<img src="/public/logo.png"/>'
url:                http://lithekod.se
baseurl:            ''
paginate:           5

# About/contact
author:
  name:             LiTHe kod
  url:              https://www.facebook.com/LitheKod/
  email:            pr@lithekod.se

# Custom vars
version:            1.0.0

gems: [jekyll-paginate]
