# Permalinks
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num"

# Setup
title:              LiTHe kod
tagline:            ''
description:        '<img src="/public/logo.png"/>'
url:                http://lithekod.se
baseurl:            ''
paginate:           5

# About/contact
author:
  name:             LiTHe kod
  url:              https://www.facebook.com/LitheKod/
  email:            pr@lithekod.se

# Custom vars
version:            1.0.0
github:             "https://github.com/lithekod"
protocols:          "https://github.com/lithekod/protocols"
byelaws:            "https://drive.google.com/file/d/0B7-h8_ZZQL3uMjEtNzVQOUlVcGc/view?usp=sharing"

gems: [jekyll-paginate]
